title: ""
email: ""
description: ""

baseurl: "" # jangan dikasih slash
url: "https://cerita-seks.github.io"

permalink: "/:title.html"

# Sosial Media
twitter_username: ""
github_username: "cerdew"

# Pagination
paginate: 10
paginate_path: "/page/:num/"

# Build
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
# File dan folder yang tidak perlu diproses
exclude:
  - README.md
  - node_modules
  - tailwind.config.js
  - postcss.config.js
  - package.json
  - package-lock.json
